const MydataCard = [
  {
    id: 1,
    image: "/public/First.jpg",
    by: "by",
    bypaxi: "Determinrd-poitras",
    bold: "Create an LMS Website with LearnPress",
    weeks: "2weeks",
    students: "156 students",
    pricebefore: "$29.0",
    pricenow: "Free",
    lastbutton: "View More",
  },
  {
    id: 2,
    image: "/public/second.jpg",
    by: "by",
    bypaxi: "Determinrd-poitras",
    bold: "Design a website with ThimPress",
    weeks: "2weeks",
    students: "156 students",
    pricebefore: "$29.0",
    pricenow: "$49.0",
    lastbutton: "View More",
  },
  {
    id: 3,
    image: "/public/third.jpg",
    by: "by",
    bypaxi: "Determinrd-poitras",
    bold: "Create an LMS Website with LearnPress",
    weeks: "2weeks",
    students: "156 students",
    pricebefore: "$29.0",
    pricenow: "Free",
    lastbutton: "View More",
  },
  {
    id: 4,
    image: "/public/third.jpg",
    by: "by",
    bypaxi: "Determinrd-poitras",
    bold: "Create an LMS Website with LearnPress",
    weeks: "2weeks",
    students: "156 students",
    pricebefore: "$29.0",
    pricenow: "Free",
    lastbutton: "View More",
  },
];
export default MydataCard;
